apiVersion: v1
kind: PersistentVolume
metadata:
  name: ap-database-pv
  namespace: ap-database
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/ap-database-data"
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
