apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ap-databse-mysql
    name: ap-database-pvc-ebs
  name: ap-database-pvc-ebs
  namespace: ap-database

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc
