apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: r-db-mysql
    name: r-db-pvc
  name: r-db-pvc-ebs
  namespace: rm-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ebs-sc
