apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: r-mysql-db
  name: r-pvc
  namespace: rm-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: r-pv
