apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ap-database-pvc
  namespace: ap-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
