apiVersion: v1
kind: Service
metadata:
  name: ap-database-service
  namespace: ap-database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: ap-database-mysql
  clusterIP: None
