apiVersion: v1
kind: PersistentVolume
metadata:
  name: r-db-pv
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/r-db-data"
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem
