kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: rm-db 
  name: r-db-pvc
  labels:
    name: r-db-pvc

spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
