apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-db-deploy
  namespace: rm-db
spec:
  selector:
    matchLabels:
      app: r-db-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: r-db-mysql
    spec:
      containers:
      - image: mysql
        name: r-db-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: r-db-secret
              key: DB_PASS
              optional: false
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: r-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: r-db-svc
  namespace: rm-db
  labels:
    app: r-db-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: r-db-mysql
