apiVersion: v1
kind: Service
metadata:
  name: r-db-svc
  namespace: rm-db
  labels:
    app: r-mysql-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: r-mysql-db
  clusterIP: None
