apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: r-ingress
  namespace: rm-webapp
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - pathType: Prefix
          path: /webapp(/|$)(.*)
          backend:
            service:
              name: r-webapp-svc
              port:
                number: 80