apiVersion: apps/v1
kind: Deployment
metadata:
  name: apopa-webapp
  namespace: ap-webapp
spec:
  selector:
    matchLabels:
      run: devops-webapp-sample
  replicas: 1
  template:
    metadata:
      labels:
        run: devops-webapp-sample
    spec:
      containers:
        - name: apopa-webapp
          image: revianlabs/devops-webapp-sample:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "h2"
            - name: DB_URL
              value: jdbc:mysql://ap-database-service.ap-database.svc.cluster.local:3306/mysql
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ap-database-creds
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: ap-database-creds
                  key: pass
          ports:
            - containerPort: 8080
      nodeSelector: 
        topology.ebs.csi.aws.com/zone: "eu-central-1a"
        
